#!/usr/bin/env python3
"""Tested by Cat

re-write of catlock, using PyQt5

Screen lock program using assets generated by badabing
 
retain name catlock? Balthazar is still Test Kitty #1. 
I can't use it myself if it can't protect from my cat!


"""

import os, sys, getopt, getpass, pwd
# from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QShortcut
# from PyQt5.QtGui import QIcon, QPixmap, QRegExpValidator, QFont, QImage, QKeySequence
# from PyQt5.QtCore import Qt, pyqtSlot, QRegExp, QTimer, QTime, QDateTime

print(os.uname().sysname)